
version: '2'

services:

  mfan:
    build: .
    image: mfan:3.9
    container_name: mfan
    volumes:
      - ./:/app
      - /data/dcdb/mfans:/app/data
    working_dir: /app
    ports: 
      - 27004:27004
    command: "python /app/app.py"
    restart: always